# Generated by Django 4.1.1 on 2022-10-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='item',
            field=models.CharField(default=None, max_length=500000000000000000),
        ),
    ]
