# Generated by Django 4.1.1 on 2022-10-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_todo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='userImages'),
        ),
    ]
